# Generated by Django 5.1.3 on 2026-01-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
