# Generated by Django 5.1.3 on 2026-01-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_skill_icon_skill_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image_url',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
