# Generated by Django 6.1 on 2026-08-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_emaillog_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
