# Generated by Django 6.1 on 2026-08-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_client_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='country_code',
            field=models.CharField(blank=True, default='TZ', max_length=5),
        ),
    ]
